apiVersion: v1
kind: Service
metadata:
  name: mongo-service
spec:
  selector:
    app: mongo  # Must match the label in the Deployment
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
